trigger:
  branches:
    include:
    - main
  paths:
   include:
     - '.azdo/uwp-dev.yml'
     - 'src/Uwp/**/*'

variables:
  DOTNET_SDK_VERSION: '10.0.x'
  BUILD_CONFIG: 'Debug'
  BUILD_PLAT: 'x64'
  nugetConfigPath: 'src/NuGet.Config'
  uwpProjectPath: 'src/MvpApi.Uwp/MvpApi.Uwp.csproj'

jobs:
- job: BuildUwpApp
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: $(DOTNET_SDK_VERSION)

  - powershell: dotnet nuget update source 'Telerik_v3_Server' -s 'https://nuget.telerik.com/v3/index.json' -u 'api-key' -p '$(TELERIK-NUGET-KEY)' --store-password-in-clear-text --configfile '$(nugetConfigPath)'
    displayName: 'Update NuGet Credentials'

  - powershell: dotnet restore $(uwpProjectPath) --configfile $(nugetConfigPath)
    displayName: 'Restore NuGet Packages'

  - powershell: msbuild $(uwpProjectPath) /t:Restore /p:Configuration=$(BUILD_PLAT)
    displayName: 'MSBuild Restore'

  - task: MSBuild@1
    displayName: 'MSBuild Build'
    inputs:
      solution: '$(uwpProjectPath)'
      platform: $(BUILD_CONFIG)
      configuration: $(BUILD_PLAT)
      msbuildArguments: '/p:AppxBundlePlatforms="x64|arm64"
                         /p:UapAppxPackageBuildMode=CI
                         /p:AppxBundle=Never 
                         /p:PackageCertificateKeyFile="$(PfxDownloadStep.secureFilePath)" 
                         /p:PackageCertificatePassword="$(PfxPassword)" 
                         /p:PackageCertificateThumbprint="" 
                         /p:AppxPackageDir="$(Build.ArtifactStagingDirectory)/AppPackages" 
                         /p:GenerateAppxPackageOnBuild=true 
                         /p:AppxPackageSigningEnabled=false 
                         /p:SelfContained=true'
    env:
      TELERIK_LICENSE: $(TelerikLicenseKey)
