// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Models
{
    public partial class ContributionsModel
    {
        /// <summary>
        /// Initializes a new instance of the ContributionsModel class.
        /// </summary>
        public ContributionsModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionsModel class.
        /// </summary>
        public ContributionsModel(int? contributionId = default(int?), string contributionTypeName = default(string), ContributionTypeModel contributionType = default(ContributionTypeModel), ContributionTechnologyModel contributionTechnology = default(ContributionTechnologyModel), DateTime? startDate = default(DateTime?), string title = default(string), string referenceUrl = default(string), VisibilityViewModel visibility = default(VisibilityViewModel), int? annualQuantity = default(int?), int? secondAnnualQuantity = default(int?), int? annualReach = default(int?), string description = default(string))
        {
            ContributionId = contributionId;
            ContributionTypeName = contributionTypeName;
            ContributionType = contributionType;
            ContributionTechnology = contributionTechnology;
            StartDate = startDate;
            Title = title;
            ReferenceUrl = referenceUrl;
            Visibility = visibility;
            AnnualQuantity = annualQuantity;
            SecondAnnualQuantity = secondAnnualQuantity;
            AnnualReach = annualReach;
            Description = description;
        }

        /// <summary>
        /// Gets or sets the Contribution table id.
        /// </summary>
        [JsonProperty(PropertyName = "ContributionId")]
        public int? ContributionId { get; set; }

        /// <summary>
        /// Name of the contribution type
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTypeName")]
        public string ContributionTypeName { get; set; }

        /// <summary>
        /// Gets or sets the contribution type.
        /// </summary>
        [JsonProperty(PropertyName = "ContributionType")]
        public ContributionTypeModel ContributionType { get; set; }

        /// <summary>
        /// Gets or sets the contribution technology.
        /// </summary>
        [JsonProperty(PropertyName = "ContributionTechnology")]
        public ContributionTechnologyModel ContributionTechnology { get; set; }

        /// <summary>
        /// Gets or sets the start date.
        /// </summary>
        [JsonProperty(PropertyName = "StartDate")]
        public DateTime? StartDate { get; set; }

        /// <summary>
        /// Gets or sets the title.
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or sets the url.
        /// </summary>
        [JsonProperty(PropertyName = "ReferenceUrl")]
        public string ReferenceUrl { get; set; }

        /// <summary>
        /// Gets or sets the visibility.
        /// </summary>
        [JsonProperty(PropertyName = "Visibility")]
        public VisibilityViewModel Visibility { get; set; }

        /// <summary>
        /// Gets or sets the annual quantity.
        /// </summary>
        [JsonProperty(PropertyName = "AnnualQuantity")]
        public int? AnnualQuantity { get; set; }

        /// <summary>
        /// Gets or sets the second annual quantity.
        /// </summary>
        [JsonProperty(PropertyName = "SecondAnnualQuantity")]
        public int? SecondAnnualQuantity { get; set; }

        /// <summary>
        /// Gets or sets the reach score.
        /// </summary>
        [JsonProperty(PropertyName = "AnnualReach")]
        public int? AnnualReach { get; set; }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description { get; set; }

    }
}
