// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class ContributionTechnologyModel : ObservableObject
    {
        private Guid? id;
        private string awardCategory;
        private string awardName;
        private string name;
        private int? statuscode;
        private bool? active;

        /// <summary>
        /// Initializes a new instance of the ContributionTechnologyModel class.
        /// </summary>
        public ContributionTechnologyModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionTechnologyModel class.
        /// 
        /// If this model is instantiated from MvpApiService.GetContributionsAsync, it will use this CTOR
        /// </summary>
        public ContributionTechnologyModel(Guid? id = default(Guid?), string name = default(string), string awardName = default(string), string awardCategory = default(string))
        {
            Id = id;
            Name = name;
            AwardName = awardName;
            AwardCategory = awardCategory;
        }

        /// <summary>
        /// Initializes a new instance of the ContributionTechnologyModel class.
        /// 
        /// If this model is instantiated from MvpApiService.GetContributionAreasAsync(), it will use this CTOR
        /// </summary>
        public ContributionTechnologyModel(Guid? id = default(Guid?), string name = default(string), string awardName = default(string), string awardCategory = default(string), int statusCode = default(int), bool active = default(bool))
        {
            Id = id;
            Name = name;
            AwardName = awardName;
            AwardCategory = awardCategory;
            Statuscode = statuscode;
            Active = active;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id
        {
            get => id;
            set => SetProperty(ref id, value);
        }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name
        {
            get => name;
            set => SetProperty(ref name, value);
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardName")]
        public string AwardName
        {
            get => awardName;
            set => SetProperty(ref awardName, value);
        }

        /// <summary>
        /// Property to hold the Award Category value
        /// </summary>
        [JsonProperty(PropertyName = "AwardCategory")]
        public string AwardCategory
        {
            get => awardCategory;
            set => SetProperty(ref awardCategory, value);
        }

        [JsonProperty(PropertyName = "Statuscode")]
        public int? Statuscode
        {
            get => statuscode;
            set => SetProperty(ref statuscode, value);
        }

        [JsonProperty(PropertyName = "Active")]
        public bool? Active
        {
            get => active;
            set => SetProperty(ref active, value);
        }
    }
}