// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class ContributionViewModel
    {
        /// <summary>
        /// Initializes a new instance of the ContributionViewModel class.
        /// </summary>
        public ContributionViewModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionViewModel class.
        /// </summary>
        public ContributionViewModel(IList<ContributionsModel> contributions = default(IList<ContributionsModel>), int? totalContributions = default(int?), int? pagingIndex = default(int?))
        {
            Contributions = contributions;
            TotalContributions = totalContributions;
            PagingIndex = pagingIndex;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contributions")]
        public IList<ContributionsModel> Contributions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TotalContributions")]
        public int? TotalContributions { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PagingIndex")]
        public int? PagingIndex { get; set; }
    }
}
