// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class ContributionTechnologyModel
    {
        /// <summary>
        /// Initializes a new instance of the ContributionTechnologyModel
        /// class.
        /// </summary>
        public ContributionTechnologyModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionTechnologyModel
        /// class.
        /// </summary>
        public ContributionTechnologyModel(Guid? id = default(Guid?), string name = default(string), string awardName = default(string), string awardCategory = default(string))
        {
            Id = id;
            Name = name;
            AwardName = awardName;
            AwardCategory = awardCategory;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public Guid? Id { get; set; }

        /// <summary>
        /// Gets or sets the name.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AwardName")]
        public string AwardName { get; set; }

        /// <summary>
        /// Property to hold the Award Category value
        /// </summary>
        [JsonProperty(PropertyName = "AwardCategory")]
        public string AwardCategory { get; set; }
    }
}
