// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class MvpHighlightViewModel
    {
        /// <summary>
        /// Initializes a new instance of the MvpHighlightViewModel class.
        /// </summary>
        public MvpHighlightViewModel() { }

        /// <summary>
        /// Initializes a new instance of the MvpHighlightViewModel class.
        /// </summary>
        public MvpHighlightViewModel(string title = default(string), DateTime? date = default(DateTime?), string dateFormatted = default(string), string url = default(string), string type = default(string), string language = default(string))
        {
            Title = title;
            Date = date;
            DateFormatted = dateFormatted;
            Url = url;
            Type = type;
            Language = language;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Title")]
        public string Title { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Date")]
        public DateTime? Date { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DateFormatted")]
        public string DateFormatted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Language")]
        public string Language { get; set; }
    }
}
