// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class OnlineIdentity
    {
        /// <summary>
        /// Initializes a new instance of the OnlineIdentity class.
        /// </summary>
        public OnlineIdentity() { }

        /// <summary>
        /// Initializes a new instance of the OnlineIdentity class.
        /// </summary>
        public OnlineIdentity(Guid? onlineIdentityId = default(Guid?), Guid? mvpGuid = default(Guid?), string name = default(string), int? privateSiteId = default(int?), SharingPreference onlineIdentityVisibility = default(SharingPreference), SocialNetwork socialNetwork = default(SocialNetwork), string url = default(string), string displayName = default(string), string userId = default(string), string microsoftAccount = default(string), bool? contributionCollected = default(bool?), bool? privacyConsentStatus = default(bool?), bool? submitted = default(bool?))
        {
            OnlineIdentityId = onlineIdentityId;
            MvpGuid = mvpGuid;
            Name = name;
            PrivateSiteId = privateSiteId;
            OnlineIdentityVisibility = onlineIdentityVisibility;
            SocialNetwork = socialNetwork;
            Url = url;
            DisplayName = displayName;
            UserId = userId;
            MicrosoftAccount = microsoftAccount;
            ContributionCollected = contributionCollected;
            PrivacyConsentStatus = privacyConsentStatus;
            Submitted = submitted;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OnlineIdentityId")]
        public Guid? OnlineIdentityId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MvpGuid")]
        public Guid? MvpGuid { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrivateSiteId")]
        public int? PrivateSiteId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OnlineIdentityVisibility")]
        public SharingPreference OnlineIdentityVisibility { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SocialNetwork")]
        public SocialNetwork SocialNetwork { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Url")]
        public string Url { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "DisplayName")]
        public string DisplayName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UserId")]
        public string UserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "MicrosoftAccount")]
        public string MicrosoftAccount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContributionCollected")]
        public bool? ContributionCollected { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PrivacyConsentStatus")]
        public bool? PrivacyConsentStatus { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Submitted")]
        public bool? Submitted { get; set; }

    }
}
