// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class SocialNetwork
    {
        /// <summary>
        /// Initializes a new instance of the SocialNetwork class.
        /// </summary>
        public SocialNetwork() { }

        /// <summary>
        /// Initializes a new instance of the SocialNetwork class.
        /// </summary>
        public SocialNetwork(Guid? socialNetworkId = default(Guid?), string name = default(string), string website = default(string), SocialNetworkStatusCode statusCode = default(SocialNetworkStatusCode), bool? systemCollectionEnabled = default(bool?))
        {
            SocialNetworkId = socialNetworkId;
            Name = name;
            Website = website;
            StatusCode = statusCode;
            SystemCollectionEnabled = systemCollectionEnabled;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SocialNetworkId")]
        public Guid? SocialNetworkId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Website")]
        public string Website { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StatusCode")]
        public SocialNetworkStatusCode StatusCode { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SystemCollectionEnabled")]
        public bool? SystemCollectionEnabled { get; set; }

    }
}
