// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
	/// <summary>
	/// The activity view model.
	///Note:
	///The logic of acticity is a little complicate.
	///While edit activity, the ActivityType should be non-editable;
	///While add activity, the dispalyname of AnnualQuantity/SecondAnnualQuantity/ReachScore should change with ActivityType changing,
	///and validation rule is different while ActivityType change.
	///Following is the logic details.
	///<remarks>
	///Book (Author):
	///    [msft_title: required, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_annualquantity: required, 'Books']
	///Book (Co-Author): same as Book (Author)
	///Conference (booth presenter):
	///    [msft_title: required, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_annualquantity: required, 'Conferences']
	///Conference (organizer): same as Conference (booth presenter)
	///Speaking (Conference):
	///    [msft_title: required, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_annualquantity: required, 'Talks']
	///Speaking (Local):Same as Speaking (Conference)
	///Speaking (User group):Same as Speaking (Conference)
	///Forum Moderator:
	///    [msft_title: required, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_annualquantity: required, 'Threads Moderated']
	///Forum Participation (Microsoft Forums):
	///    [msft_title: recommend, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_url: required, 'Url']
	///    [msft_annualquantity: required, 'Answers']
	///Forum Participation (3rd Party forums):
	///    [msft_title: recommend, 'Title']
	///    [msft_startdate: required,'Start Date']
	///    [msft_url: required, 'Url']
	///    [msft_annualquantity: required, 'Answers']
	///    [msft_secondannualquantity: required, 'Posts']
	///</remarks>
	/// </summary>
	public class ActivityViewModel
	{

		/// <summary>
		/// Gets or sets the private site id.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "PrivateSiteId")]
		public System.Int32? PrivateSiteId { get; set; }

		/// <summary>
		/// The activity type.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "ActivityType")]
		public ActivityTypeViewModel ActivityType { get; set; }

		/// <summary>
		/// The activity technology model.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "ApplicableTechnology")]
		public ActivityTechnologyViewModel ApplicableTechnology { get; set; }

		/// <summary>
		/// Gets or sets the start date.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "DateOfActivity")]
		public System.DateTimeOffset DateOfActivity { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DateOfActivityFormatted")]
		public string DateOfActivityFormatted { get; set; }

		/// <summary>
		/// End Date for system auto contribution
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "EndDate")]
		public System.DateTimeOffset? EndDate { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "EndDateFormatted")]
		public string EndDateFormatted { get; set; }

		/// <summary>
		/// Gets or sets the title.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "TitleOfActivity")]
		public string TitleOfActivity { get; set; }

		/// <summary>
		/// Gets or sets the url.
		/// Pattern: ^((https?|ftp):\/\/)?(((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)+(\/(([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)|\/|\?)*)?$
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "ReferenceUrl")]
		public string ReferenceUrl { get; set; }

		/// <summary>
		/// The visibility.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "ActivityVisibility")]
		public VisibilityViewModel ActivityVisibility { get; set; }

		/// <summary>
		/// Gets or sets the annual quantity.
		/// Pattern: ^[0-9]*$
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "AnnualQuantity")]
		public System.Int32? AnnualQuantity { get; set; }

		/// <summary>
		/// Gets or sets the second annual quantity.
		/// Pattern: ^[0-9]*$
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "SecondAnnualQuantity")]
		public System.Int32? SecondAnnualQuantity { get; set; }

		/// <summary>
		/// Gets or sets the reach score.
		/// Pattern: ^[0-9]*$
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "AnnualReach")]
		public System.Int32? AnnualReach { get; set; }

		/// <summary>
		/// Gets or sets the description.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
		public string Description { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "OnlineIdentity")]
		public OnlineIdentityViewModel OnlineIdentity { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "SocialNetwork")]
		public SocialNetworkViewModel SocialNetwork { get; set; }

		/// <summary>
		/// AllAnswersUrl
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "AllAnswersUrl")]
		public string AllAnswersUrl { get; set; }

		/// <summary>
		/// AllAnswersUrl
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "AllPostsUrl")]
		public string AllPostsUrl { get; set; }

		/// <summary>
		/// If this contribution is system collected
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "IsSystemCollected")]
		public System.Boolean? IsSystemCollected { get; set; }

		/// <summary>
		/// If this contribution belongs to latest award cycle.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "IsBelongToLatestAwardCycle")]
		public System.Boolean? IsBelongToLatestAwardCycle { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DisplayMode")]
		public string DisplayMode { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "ChartColumnIndexes")]
		public int[] ChartColumnIndexes { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DescriptionSummaryFormat")]
		public string DescriptionSummaryFormat { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DataTableTitle")]
		public string DataTableTitle { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "SubtitleHeader")]
		public string SubtitleHeader { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "IsAllowEdit")]
		public System.Boolean? IsAllowEdit { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "IsAllowDelete")]
		public System.Boolean? IsAllowDelete { get; set; }

		/// <summary>
		/// IsBookmarklet: If the call is initiated from bookmarklet
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "IsFromBookmarklet")]
		public System.Boolean? IsFromBookmarklet { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Submitted")]
		public System.Boolean? Submitted { get; set; }
	}
}
