// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    /// <summary>
    /// The account certification view model for edit.
    /// </summary>
    public class CertificationViewModel
    {
        /// <summary>
        /// Initializes a new instance of the CertificationViewModel class.
        /// </summary>
        public CertificationViewModel() { }

        public CertificationViewModel(int? privateSiteId, string id, string title, VisibilityViewModel certificationVisibility)
        {
            PrivateSiteId = privateSiteId;
            Id = id;
            Title = title;
            CertificationVisibility = certificationVisibility;
        }

        /// <summary>
        /// Gets or sets the private site id.
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "PrivateSiteId")]
		public System.Int32? PrivateSiteId { get; set; }

		/// <summary>
		/// Gets or sets the id.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
		public string Id { get; set; }

		/// <summary>
		/// Gets or sets the title.
		/// Max length: 100
		/// Min length: 0
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "Title")]
		public string Title { get; set; }

		/// <summary>
		/// The visibility.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "CertificationVisibility")]
		public VisibilityViewModel CertificationVisibility { get; set; }
	}
}
