// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class ContentMetadata
    {
        /// <summary>
        /// Initializes a new instance of the ContentMetadata class.
        /// </summary>
        public ContentMetadata() { }

        public ContentMetadata(string pageTitle, string templateName, string keywords, string description)
        {
            PageTitle = pageTitle;
            TemplateName = templateName;
            Keywords = keywords;
            Description = description;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "PageTitle")]
		public string PageTitle { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "TemplateName")]
		public string TemplateName { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Keywords")]
		public string Keywords { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Description")]
		public string Description { get; set; }
	}
}
