// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using CommonHelpers.Common;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class ContributionTypeModel : BindableBase
    {
        private string id;
        private string name;
        private string englishName;

        /// <summary>
        /// Initializes a new instance of the ContributionTypeModel class.
        /// </summary>
        public ContributionTypeModel() { }

        /// <summary>
        /// Initializes a new instance of the ContributionTypeModel class.
        /// </summary>
        public ContributionTypeModel(string id, string name = default, string englishName = default)
        {
            Id = id;
            Name = name;
            EnglishName = englishName;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public string Id
        {
            get => id;
            set => SetProperty(ref id, value);
        }

        /// <summary>
        /// Gets or sets the localized name.
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name
        {
            get => name;
            set => SetProperty(ref name, value);
        }

        /// <summary>
        /// Gets or sets the english name
        /// </summary>
        [JsonProperty(PropertyName = "EnglishName")]
        public string EnglishName
        {
            get => englishName;
            set => SetProperty(ref englishName, value);
        }
    }
}