// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class MvpHighlightViewModel
    {
        /// <summary>
        /// Initializes a new instance of the MvpHighlightViewModel class.
        /// </summary>
        public MvpHighlightViewModel() { }

        public MvpHighlightViewModel(string title, DateTimeOffset? date, string dateFormatted, string url, string type, string language)
        {
            Title = title;
            Date = date;
            DateFormatted = dateFormatted;
            Url = url;
            Type = type;
            Language = language;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "Title")]
		public string Title { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Date")]
		public System.DateTimeOffset? Date { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DateFormatted")]
		public string DateFormatted { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Url")]
		public string Url { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
		public string Type { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Language")]
		public string Language { get; set; }
	}
}
