// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class OnlineIdentityViewModel
    {
        /// <summary>
        /// Initializes a new instance of the OnlineIdentityViewModel class.
        /// </summary>
        public OnlineIdentityViewModel() { }

        public OnlineIdentityViewModel(int? privateSiteId, SocialNetworkViewModel socialNetwork, string url, VisibilityViewModel onlineIdentityVisibility, bool? contributionCollected, string displayName, string userId, string microsoftAccount, bool? privacyConsentStatus, bool? privacyConsentCheckStatus, DateTimeOffset? privacyConsentCheckDate, DateTimeOffset? privacyConsentUnCheckDate, bool? submitted)
        {
            PrivateSiteId = privateSiteId;
            SocialNetwork = socialNetwork;
            Url = url;
            OnlineIdentityVisibility = onlineIdentityVisibility;
            ContributionCollected = contributionCollected;
            DisplayName = displayName;
            UserId = userId;
            MicrosoftAccount = microsoftAccount;
            PrivacyConsentStatus = privacyConsentStatus;
            PrivacyConsentCheckStatus = privacyConsentCheckStatus;
            PrivacyConsentCheckDate = privacyConsentCheckDate;
            PrivacyConsentUnCheckDate = privacyConsentUnCheckDate;
            Submitted = submitted;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "PrivateSiteId")]
		public System.Int32? PrivateSiteId { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "SocialNetwork")]
		public SocialNetworkViewModel SocialNetwork { get; set; }

		/// <summary>
		/// Max length: 490
		/// Min length: 0
		/// Pattern: ^((https?|ftp):\/\/)?(((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:)*@)?(((\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5])\.(\d|[1-9]\d|1\d\d|2[0-4]\d|25[0-5]))|((([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-zA-Z]|\d|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.)+(([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])*([a-zA-Z]|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])))\.?)(:\d*)?)(\/((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)+(\/(([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)*)*)?)?(\?((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)|[\uE000-\uF8FF]|\/|\?)*)?(\#((([a-zA-Z]|\d|-|\.|_|~|[\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])|(%[\da-fA-F]{2})|[!\$&amp;'\(\)\*\+,;=]|:|@)|\/|\?)*)?$
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "Url")]
		public string Url { get; set; }

		/// <summary>
		/// The visibility.
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "OnlineIdentityVisibility")]
		public VisibilityViewModel OnlineIdentityVisibility { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "ContributionCollected")]
		public System.Boolean? ContributionCollected { get; set; }

		/// <summary>
		/// Max length: 500
		/// Min length: 0
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "DisplayName")]
		public string DisplayName { get; set; }

		/// <summary>
		/// Max length: 500
		/// Min length: 0
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "UserId")]
		public string UserId { get; set; }

		/// <summary>
		/// Max length: 500
		/// Min length: 0
		/// </summary>
		[Newtonsoft.Json.JsonProperty(PropertyName = "MicrosoftAccount")]
		public string MicrosoftAccount { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "PrivacyConsentStatus")]
		public System.Boolean? PrivacyConsentStatus { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "PrivacyConsentCheckStatus")]
		public System.Boolean? PrivacyConsentCheckStatus { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "PrivacyConsentCheckDate")]
		public System.DateTimeOffset? PrivacyConsentCheckDate { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "PrivacyConsentUnCheckDate")]
		public System.DateTimeOffset? PrivacyConsentUnCheckDate { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Submitted")]
		public System.Boolean? Submitted { get; set; }
	}
}
