// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class ProfileViewModel
    {
        public ProfileViewModel() { }

        public ProfileViewModel(ContentMetadata metadata, string mvpId, int? yearsAsMvp, string firstAwardYear, string awardCategoryDisplay, string technicalExpertise, bool? inTheSpotlight, string headline, string biography, string displayName, string fullName, string primaryEmailAddress, string shippingCountry, string shippingStateCity, string languages, IList<OnlineIdentityViewModel> onlineIdentities, IList<CertificationViewModel> certifications, IList<ActivityViewModel> activities, IList<AwardRecognitionViewModel> communityAwards, IList<MvpHighlightViewModel> newsHighlights, IList<MvpHighlightViewModel> upcomingEvent)
        {
            Metadata = metadata;
            MvpId = mvpId;
            YearsAsMvp = yearsAsMvp;
            FirstAwardYear = firstAwardYear;
            AwardCategoryDisplay = awardCategoryDisplay;
            TechnicalExpertise = technicalExpertise;
            InTheSpotlight = inTheSpotlight;
            Headline = headline;
            Biography = biography;
            DisplayName = displayName;
            FullName = fullName;
            PrimaryEmailAddress = primaryEmailAddress;
            ShippingCountry = shippingCountry;
            ShippingStateCity = shippingStateCity;
            Languages = languages;
            OnlineIdentities = onlineIdentities;
            Certifications = certifications;
            Activities = activities;
            CommunityAwards = communityAwards;
            NewsHighlights = newsHighlights;
            UpcomingEvent = upcomingEvent;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "Metadata")]
		public ContentMetadata Metadata { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "MvpId")]
		public string MvpId { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "YearsAsMvp")]
		public System.Int32? YearsAsMvp { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "FirstAwardYear")]
		public string FirstAwardYear { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "AwardCategoryDisplay")]
		public string AwardCategoryDisplay { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "TechnicalExpertise")]
		public string TechnicalExpertise { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "InTheSpotlight")]
		public System.Boolean? InTheSpotlight { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Headline")]
		public string Headline { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Biography")]
		public string Biography { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "DisplayName")]
		public string DisplayName { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "FullName")]
		public string FullName { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "PrimaryEmailAddress")]
		public string PrimaryEmailAddress { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "ShippingCountry")]
		public string ShippingCountry { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "ShippingStateCity")]
		public string ShippingStateCity { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Languages")]
		public string Languages { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "OnlineIdentities")]
		public IList<OnlineIdentityViewModel> OnlineIdentities { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Certifications")]
		public IList<CertificationViewModel> Certifications { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Activities")]
		public IList<ActivityViewModel> Activities { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "CommunityAwards")]
		public IList<AwardRecognitionViewModel> CommunityAwards { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "NewsHighlights")]
		public IList<MvpHighlightViewModel> NewsHighlights { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "UpcomingEvent")]
		public IList<MvpHighlightViewModel> UpcomingEvent { get; set; }
	}
}
