// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class SocialNetwork
    {
        /// <summary>
        /// Initializes a new instance of the SocialNetwork class.
        /// </summary>
        public SocialNetwork() { }

        public SocialNetwork(string socialNetworkId, string name, string website, SocialNetworkStatusCode statusCode, bool? systemCollectionEnabled)
        {
            SocialNetworkId = socialNetworkId;
            Name = name;
            Website = website;
            StatusCode = statusCode;
            SystemCollectionEnabled = systemCollectionEnabled;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "SocialNetworkId")]
		public string SocialNetworkId { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
		public string Name { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Website")]
		public string Website { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "StatusCode")]
		public SocialNetworkStatusCode StatusCode { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "SystemCollectionEnabled")]
		public System.Boolean? SystemCollectionEnabled { get; set; }
	}
}
