// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public class SocialNetworkViewModel
    {
        public SocialNetworkViewModel() { }

        public SocialNetworkViewModel(string id, string name, string iconUrl, bool? systemCollectionEnabled)
        {
            Id = id;
            Name = name;
            IconUrl = iconUrl;
            SystemCollectionEnabled = systemCollectionEnabled;
        }

        [Newtonsoft.Json.JsonProperty(PropertyName = "Id")]
		public string Id { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "Name")]
		public string Name { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "IconUrl")]
		public string IconUrl { get; set; }

		[Newtonsoft.Json.JsonProperty(PropertyName = "SystemCollectionEnabled")]
		public System.Boolean? SystemCollectionEnabled { get; set; }
	}
}
