// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using CommonHelpers.Common;
using Newtonsoft.Json;

namespace MvpApi.Common.Models
{
    public partial class VisibilityViewModel : BindableBase
    {
        private int? id;
        private string description;
        private string localizeKey;

        public VisibilityViewModel() { }

        public VisibilityViewModel(int? id, string description, string localizeKey)
        {
            Id = id;
            Description = description;
            LocalizeKey = localizeKey;
        }

        /// <summary>
        /// Gets or sets the id.
        /// </summary>
        [JsonProperty(PropertyName = "Id")]
        public int? Id
        {
            get => id;
            set => SetProperty(ref id, value);
        }

        /// <summary>
        /// Gets or sets the description.
        /// </summary>
        [JsonProperty(PropertyName = "Description")]
        public string Description
        {
            get => description;
            set => SetProperty(ref description, value);
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LocalizeKey")]
        public string LocalizeKey
        {
            get => localizeKey;
            set => SetProperty(ref localizeKey, value);
        }
    }
}
